### ISSUE TITLE
missing settings.php

### ISSUE THREAD

**Issue by helloasir** [ZachariasAthanasios/MyPelatologio#1]
seems you missed settings.php

**Comment by ZachariasAthanasios** [comment]
Hey there, the project has not yet been completed. The settings page does not exist and the search does not work. I hope to finish it by Friday. Thank you very much for your comment, any question or suggestion is welcome.

**Comment by ZachariasAthanasios** [comment]
> seems you missed settings.php

Hey there, the project has not yet been completed. The settings page does not exist and the search does not work. I hope to finish it by Friday. Thank you very much for your comment, any question or suggestion is welcome.
